import local from "next/font/local";
import "./globals.css";

const gilroy = local({
  src: [
    {
      path: "../public/fonts/Gilroy-ExtraBold.otf",
      weight: "700",
    },
    {
      path: "../public/fonts/Gilroy-Light.otf",
      weight: "400",
    },
  ],
  variable: "--font-gilroy",
});

export const metadata = {
  title: "Brainwave.io",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gilroy.className} antialiased`}>{children}</body>
    </html>
  );
}
